### ISSUE TITLE
apps.yaml

### ISSUE THREAD

**Issue by JasonMADCow** [idodov/pixoo64-media-album-art#1]
Can't seem to just paste yaml. GIves yaml foramtting issues?

can not read a block mapping entry; a multiline key may not be an implicit key (8:24)

**Comment by JasonMADCow** [comment]
Found the problem. User error, you have to eliminate the "---" at the begginig

**Comment by idodov** [comment]
> Found the problem. User error, you have to eliminate the "---" at the begginig

Hi
The bug is in the code? I didn't understand from your post where is and if there is a problem. I don't have any issues with the original code I posted.

**Comment by idodov** [comment]
You should have only the first line in the yaml that contains the "----" line if any.

**Comment by JasonMADCow** [comment]
Sorry. No problems. Just the yaml config file


On 24 Jun 2024, at 08:29, idodov ***@***.***> wrote:

﻿

Found the problem. User error, you have to eliminate the "---" at the begginig

Hi
The bug is in the code? I didn't understand from your post where is and if there is a problem. I don't have any issues with the original code I posted.
