### ISSUE TITLE
possible bug displaying cover art due to python error with array handling in get_image()

### ISSUE THREAD

**Issue by gwiltschek** [idodov/pixoo64-media-album-art#2]
Hi there,

I was getting an Error when trying to display cover art and it defaulted back to text, so I digged around in the appdaemon log where the error message was: "INFO pixoo64_media_album_art: Error processing image. Using defualt values: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"

I traced it back to line 380 "if self.CONTRAST and not grayscale:" and and changed it to grayscale.all(). Seems to work, but since I have no real clue about python and if that error was specific to my setup of HA and appdaemon I don:t want to create a PR, so this is just for information, please disregard if the fault is on my side.

**Comment by idodov** [comment]
In rare cases, some album cover art may not display correctly due to the crop or contrast features. You can disable these features in the apps.yaml settings. What album was it? I will try to check it and debug if needed.

**Comment by gwiltschek** [comment]
It happened with every album not just some. I'm using HAOS in a VM and the official Spotify integration if that helps

**Comment by idodov** [comment]
Please ensure you have installed the correct Python packages. On the AppDaemon Configuration page, install the following Python packages: requests, numpy==1.26.4, pillow, python-bidi, and unidecode.

**Comment by gwiltschek** [comment]
I have, took the config straight from the install instructions:

system_packages: []
python_packages:
  - requests
  - unidecode
  - pillow
  - numpy==1.26.4
  - python-bidi
init_commands: []

It seems the problem originates from pillow (https://github.com/python-pillow/Pillow/issues/8220) so I guess it will be fixed there eventually and until then I just keem my fix with .all()

**Comment by idodov** [comment]
If it's the pillow package 
Try to use the previous version. 
pillow==10.3.0 

Let me know if it's fixed the issue.

**Comment by gwiltschek** [comment]
still the same error when I remove the all() from grayscale in line 380:

> Installing collected packages: pillow
> Successfully installed pillow-10.3.0
> ...
> INFO pixoo64_media_album_art: Error processing image. Using defualt values: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by idodov** [comment]
I need to investigate this issue since I’m not experiencing the error on my end. If necessary, I’ll upload a fixed version. It would be helpful if you could share a full error log.

**Comment by gwiltschek** [comment]
Are there any logfiles in particular that I can post here to help? The appdaemon logs are really just

> 2024-09-16 09:48:43.420620 INFO AppDaemon: Reloading Module: /homeassistant/appdaemon/apps/pixoo64_media_album_art.py
> 2024-09-16 09:48:43.428951 INFO AppDaemon: Loading app pixoo64_media_album_art using class Pixoo64_Media_Album_Art from module pixoo64_media_album_art
> 2024-09-16 09:48:43.430531 INFO AppDaemon: Calling initialize() for pixoo64_media_album_art
> 2024-09-16 09:49:31.690910 INFO pixoo64_media_album_art: Error processing image. Using defualt values: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
> 2024-09-16 09:50:01.690742 INFO pixoo64_media_album_art: Error processing image. Using defualt values: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
> 2024-09-16 09:50:31.902840 INFO pixoo64_media_album_art: Error processing image. Using defualt values: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by idodov** [comment]
That's all I need. Will check it and get back to you with the results

**Comment by idodov** [comment]
I checked on my end and didn't find any issues.

There are a few possible reasons why the script isn't working as expected. The script looks for the picture URL from the `media_player` entity. If it can't fetch the image, the script will fail, and you'll see a text display. You can find the URL image as an attribute `entity_picture` in the `media_player` entity (at the developer tools state screen http://homeassistant.local:8123/developer-tools/state ).

You can test this by opening a web browser with your Home Assistant URL and placing the `entity_picture` value within the link, for example image from Apple Music service (it also works with Spotify):
```
http://homeassistant.local:8123/api/media_player_proxy/media_player.era300?token=8bec7h54d0d731bz1180d93f46j932h2eee2ec21fb024f94ecded6975ee6a08a&cache=8a9b0ba3512z6246
```
If the browser downloads a file, it means you have the right network access, and this is not the problem.

The issue might be because you are using a VM, and the home network doesn't have access to the picture file, or you didn't add the permission to access it in the `configuration.yaml` file. For example:
```yaml
homeassistant:
  allowlist_external_urls:
    - http://192.168.86.10:8123             # Home Assistant IP
    - http://homeassistant.local:8123
```
---

I hope this helps!

**Comment by gwiltschek** [comment]
I think you misunderstood, everything works as long as I use grayscale.all() instead of grey scale in line 380. Only without the .all() call it falls back to text only. I tried opening the picture url in the browser first thing yesterday, that also worked, regardless of any changes to the code

**Comment by idodov** [comment]
That's unexpected, but I'm glad you found a fix that might help others. I added `.all()` to line 380, and there were no issues. I'll go ahead and publish the fix. Thank you very much for using my script!
