### ISSUE TITLE
Issue with loading module in Appdaemon

### ISSUE THREAD

**Issue by bmcgowan32** [idodov/pixoo64-media-album-art#7]
Im sure I am doing something wrong, but Ive followed the instructions to configure and I am seeing the following error in my appdeamon log:

```
2024-11-21 02:44:57.087666 INFO AppDaemon: Loading app pixoo64_media_album_art using class Pixoo64_Media_Album_Art from module pixoo64_media_album_art
2024-11-21 02:44:57.088393 WARNING AppDaemon: Unable to find class Pixoo64_Media_Album_Art in module pixoo64_media_album_art - 'pixoo64_media_album_art' is not initialized
```

Any suggestions?  I'm triple checking my config work :-)

**Comment by idodov** [comment]
It seems that the script file is not in the current directory. 

If you installed it from HACS, please note that you need to add the apps directory line in your `appdaemon.yaml` file, as described in the README page.

Let me know if this resolves the issue. 😊

**Comment by bmcgowan32** [comment]
Thanks!  I did check the appdaemon.yaml and the apps dir config.  

It actually looks like there was a change made yesterday to the module and the class name changed?  I manually grabbed the module file from a commit a few days ago, where the class name is "Pixoo64_Media_Album_Art", and it worked as expected.  

Would you mind taking a look at the most recent commit?  It looks as if there was a significant change to the .py file, including a change of the main class name?  Also, since the change to HACS 2.0, users dont appear to be able to specify a commit, meaning we can only pull in the latest version of the main branch via the HACS installation.  Would it be possible to add releases to the repo to ensure that new development doesn't impact the app?

Thanks!  This app is awesome!

**Comment by idodov** [comment]
I've rewritten the script to enhance its performance. I would appreciate it if you could try using the new code and let me know if it resolves the issue.

**Comment by idodov** [comment]
It seems that there was an issue in the new script that didn’t affect me. So, I have updated the old code again, and now everything should be fixed!

Thank you for letting me know. I will look into it.

**Comment by bmcgowan32** [comment]
Worked perfect!  Thanks so much!!!
